#!/bin/bash
START_TIME=$(date +%s)
USERID=$(id -u)

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/roboshop-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"

mkdir -p $LOGS_FOLDER
echo -e "script started execution at : $(date +%s)"

if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run th script with root access $N" | tee -a $LOG_FILE
   exit 1
else 
   echo -e "you are running with root access" | tee -a $LOG_FILE
fi

# validate function takes input as exit  status what command tried to install it
VALIDATE(){
   if [ $1 -eq 0 ]
   then 
      echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
   else 
      echo -e "installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE 
   fi    
}

cp mongo.repo /etc/yum.repos.d/mongodb.repo 
VALIADTE $? "copying mongodb repo"

dnf install mongodb-org -y | &>>$LOG_FILE 
VALIDATE $? "installing mobgodb server"

systemctl enable mongod | tee -a $LOG_FILE
VALIDATE $? "enabling mongodb"

systemctl start mongod | tee -a $LOG_FILE
VALIDATE $? "starting mongodb" 

sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf 
VALIDATE $? "Editing mongodb conf file for allow remote connections" 

systemctl restart mongod | tee -a $LOG_FILE
VALIDATE $? "restarting mongodb" 

END_TIME=$(date +%s)
TOTAL_TIME=$(( $END_TIME - $START_TIME ))

echo -e "script execution completed successfully, $Y time taken: $TOTAL_TIME seconds $N" | tee -a $LOG_FILE 