#!/bin/bash 
START_TIME=$(date +%s) 
USERID=$(id -u) 

R="\e[31m" 
G="\e[32m" 
Y="\e[33m" 
N="\e[0m" 

LOGS_FOLDER="/var/log/roboshop-logs" 
SCRIPT_NAME="$(exho $0 | cut -d "." -f1)" 
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"

mkdir -p $LOGS_FOLDER 

echo -e "script started executed at: $(date +%s)" | tee -a $LOG_FILE 

if [ $USERID -ne 0 ] 
then 
   echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE 
   exit 1 # give other than  0 upto 127 
else 
   echo "you are running with root access" 
fi 

# validate fumction takes input as exit status, whta command they tried to install 
validate(){
   if [ $1 -eq 0 ]
   then 
      echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE 
   else 
      echo -e "Installing $2 is ... $R FAILURE $N"  | tee -a $LOG_FILE 
      exit 1   
}

cp mongo.repo /etc/yum.repos.d/mongo.repo   &>> $LOG_FILE 
VALIDATE $? "Copying mongo repo" 

dnf install mongodb-org -y   &>> $LOG_FILE 
VALIDTAE $? "Installing MOngoDB" 

systemctl enable mongod  &>> $LOG_FILE 
VALIDATE $? "Enabling MongoDB"  

systemctl Start mongod &>> $LOG_FILE 
VALIDATE $? "Starting MongoDB" 

sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf  &>> $LOG_FILE 
VALIDATE $? "Editing mongod conf file for remote connections" 

systemctl restart mongod  &>> $LOG_FILE 
VALIDATE $? "Restarting MongoDB"   

END_TIME=$(date +%s) 
TOTAL_TIME=$(($END_TIME - $START_TIME)) 

echo -e "script execution completed successfully, $Y Time taken: $TOTAL_TIME seconds $N" | tee -a $LOG_FILE  
