#!/bin/bash
START_TIME=$(date +%s)
USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/roboshop-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
SCRIPT_DIR=$PWD

mkdir -p $LOGS_FOLDER
echo "Script started execution at: $(date)" | tee -a $LOG_FILE

#check the user has root privileges or not
if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
   exit 1 # give other tha 0 upto 127
else
    echo -e "you are running with root access" |  tee -a $LOG_FILE
fi 

# validate function takes input as exit status what command they tried to install
VALIDATE(){
if [ $1 -eq 0 ]
then 
    echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
else
    echo -e "INstalling $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
    exit 1
fi 
}

echo "please enter root password to setup" | tee -a $LOG_FILE 
read -s MYSQL_ROOT_PASSWORD 

dnf install mysql-server -y &>>$LOG_FILE
VALIADATE $? "Installing mysql-server"

systemctl enable mysqld | tee -a $LOG_FILE 
VALIDATE $? "Enabling mysqld" 

systemctl start mysqld | tee -a $LOG_FILE 
VALIDATE $? "Starting mysqld"
  
mysql_secure_installation --set-root-pass MYSQL_ROOT_PASSWORD | tee -a $LOG_FILE 
VALIDATE $? "setting mysql root password" 

END_TIME=$(date +%s)
TOTAL_TIME=$(( $END_TIME - $START_TIME ))

echo -e "Script execution completed successfully, $Y time taken: $TOTAL_TIME seconds $Y"| tee -a $LOG_FILE
