#!/bin/bash
START_TIME=$(date +%s)
USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/roboshop-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
SCRIPT_DIR=$PWD

mkdir -p $LOGS_FOLDER
echo "Script started execution at: $(date)" | tee -a $LOG_FILE

#check the user has root privileges or not
if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
   exit 1 # give other tha 0 upto 127
else
    echo -e "you are running with root access" |  tee -a $LOG_FILE
fi 

# validate function takes input as exit status what command they tried to install
VALIDATE(){
if [ $1 -eq 0 ]
then 
    echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
else
    echo -e "INstalling $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
    exit 1
fi 
}

dnf install python3 gcc python3-devel -y
VALIDATE $? "Installing python3 packages" 

id roboshop 
if [ $? -ne 0 ]
then 
   useradd --system --home /app --shell /sbin/nologin --comment "roboshop system user" roboshop
   VALIDATE $? "Creating roboshop system user"
else 
   echo -e "roboshop systemuser already created... $Y SKIPPING $N" 
fi 

mkdir /app 
VALIDATE $? "creating /app directory"

curl -L -o /tmp/payment.zip https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
VALIDATE $? "Download payment" 

rm -rf /app/*
cd /app 
unzip /tmp/payment.zip
VALIDATE $? "unzipping payment" 

cd /app 
pip3 install -r requirements.txt
VALIDATE $? "Installing dependencies" 

cp $SCRIPT_DIR/payment.service /etc/systemd/system/payment.service 
VALIDATE $? "Copying payment service" 

systemctl daemon-reload
VALIDATE $? "daemon reload" 

systemctl start payment 
systemctl enable payment 
VALIDATE $? "Starting payment  