#!/bin/bash
START_TIME=$(date +%s)
USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/roboshop-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
SCRIPT_DIR=$PWD

mkdir -p $LOGS_FOLDER
echo "Script started execution at: $(date)" | tee -a $LOG_FILE

#check the user has root privileges or not
if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
   exit 1 # give other tha 0 upto 127
else
    echo -e "you are running with root access" |  tee -a $LOG_FILE
fi 

# validate function takes input as exit status what command they tried to install
VALIDATE(){
if [ $1 -eq 0 ]
then 
    echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
else
    echo -e "INstalling $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
    exit 1
fi 
}

echo "please enter the root password"
read -s MYSQL_ROOT_PASSWORD

dnf install maven -y
VALIDATE $? "Installing maven or java"

id roboshop
if [ $? -ne 0 ]
then 
    useradd --system --home /app --shell /sbin/nologin --comment "roboshop system user" roboshop
    VALIDATE $? "Creating roboshop system user"
else
   echo -e " roboshop system user already created ... $Y SKIPPING $N"
fi 

mkdir -p /app 
VALIDATE $? "Creating app directory"

curl -L -o /tmp/shipping.zip https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
VALIDATE $? "Downloading shipping code"

rm -rf /app/*
cd /app 
unzip /tmp/shipping.zip
VALIDATE $? "Unzipping shipping code"

cd /app 
mvn clean package 
VALIDATE $? "packaging the shipping application" 

mv target/shipping-1.0.jar shipping.jar
VALIDATE $? "moving and renaming jar file"

cp $SCRIPT_DIR/shipping.service /etc/systemd/system/shipping.service 
VALIDATE $? "Copying shipping service" 

systemctl daemon-reload
VALIDATE $? "Daemon reload"

systemctl enable shipping 
systemctl start shipping
VALIDATE $? "Starting shipping" 

dnf install mysql -y 
VALIDATE $? "Installing mysql"

mysql -h <MYSQL-SERVER-IPADDRESS> -uroot -pMYSQL_ROOT_PASSWORD -e 'use cities' 
if [ $? -ne 0 ]
then 
    mysql -h mysql.subbuaws.site -uroot -pMYSQL_ROOT_PASSWORD < /app/db/schema.sql
    mysql -h mysql.subbuaws.site -uroot -pMYSQL_ROOT_PASSWORD < /app/db/app-user.sql 
    mysql -h mysql.subbuaws.site -uroot -pMYSQL_ROOT_PASSWORD < /app/db/master-data.sql
    VALIDATE $? "Loading data inti mysql"
else 
   echo -e "data is already loaded ... $Y SKIPPING $N"
fi 

systemctl restart shipping
VALIDATE $? "Restarting shipping"

END_TIME=$(date +%s)
TOTAL_TIME=$(( $END_TIME - $START_TIME ))

echo -e "Script executed completed successfully, $Y time taken: $TOTAL_TIME seconds $N" | tee -a $LOG_FILE

